# Site settings
title: My Website
description: Hikmet Efe Canikli's portfolio website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hikmetec.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hikmet Efe Canikli
user_description: Hello I'm Hikmet. I am student at İzmir Science High School at the moment. I am intern as a Software Developer in Codeo. I can code in several languages such as C, C++, C# and Python. I am especially work on Unity Engine and Mobile Development for a couple of years now. I worked on robotics(Arduino and RasberryPi) in the past and have general knowledge about that topic too.I've done a lot of programming and robotics projects. Some of the example projects are below..
user_title: Software Developer
email: hikmetefecanikli@gmail.com
twitter_username: HEC
github_username:  hikmetEC
gplus_username:  HEC

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
